global:
  namespace: jupyter

configMap:
  name: jupyter-notebook-configmap

deployment:
  name: jupyter-notebook-deployment
  image: nbgallery/base-notebook:notebook-6.4.4
  env:
    nbgalleryURL: https://nbgallery.jupyterathome.org

service:
  name: jupyter-notebook-service
  # Set to NodePort to access from outside the cluster
  type: "NodePort"
  externalPort: {}
  nodePort:
    http: 30146