apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
spec:
  selector:
    matchLabels:
      app: jupyter-notebook
  replicas: 1
  template:
    metadata:
      labels:
        app: jupyter-notebook
    spec:
      containers:
      - name: jupyter
        image: {{ .Values.deployment.image }}
        env:
        - name: NBGALLERY_URL
          value: {{ .Values.deployment.env.nbgalleryURL }}
        ports:
        - containerPort: 8888
        volumeMounts:
        - name: config-map
          mountPath: /opt/conda/etc/jupyter/jupyter_notebook_config.py
          subPath: jupyter_notebook_config.py
        - name: notebook-dir
          mountPath: /home/jovyan/notebooks
      volumes:
      - name: config-map
        configMap:
          name: {{ .Values.configMap.name }}
      - name: notebook-dir
        emptyDir: {}
