apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: jupyter-notebook
  ports:
  - protocol: TCP
    port: {{ .Values.service.externalPort | default 8888 }}
    targetPort: 8888
    {{ if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort.http))) }}
    nodePort: {{ .Values.service.nodePort.http }}
    {{- end -}}